#task level variables
- name: variables from play level
  hosts: localhost
  vars:
    course: "devops"
    trainer: "sri"
    duration: "3 months"
  tasks:
   - name: check variables
     vars: #task variables
      tainer: "shiva"
      course: "aws with devops"
     ansible.builtin.debug:
      msg: " hi, i m learning {{course}}, trainer is {{trainer}}, duration is {{duration}}"
