- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall
    ansible.builtin.package:
      name: "{{item}}"
      state: present # item is a default keyboard
    loop:
    - ansible
    - git
    - mysql
    - postfix
