- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall
    ansible.builtin.package:
    name: "{{item.name}}"
    state: "{{item.name}}" # item is a default keyboard
  loop:
  - {name: 'git' , state: 'present'}
  - {name: 'mysql' , state: 'absent'}
  - {name: 'postfix' , state: 'absent'}
  - {name: 'nginx' , state: 'present'}
  