- name: ping playbook
  hosts: localhost
  tasks:
  - name: ping the server
    ansible.builtin.ping:

  - name: print message
    ansible.builtin.debug:
      msg: "hi i m learning devops...all is well"
    tags:
    - devops

  - name: print message
    ansible.builtin.debug:
      msg: " hi i m learning with aws"
    tags:
    - aws